language: julia

julia:
  - nightly
  - 1.0

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; import ProteinPersistent; cd(joinpath(dirname(pathof(ProteinPersistent)), ".."));Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
